# Base configs
baseurl: "https://vsriaditya.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Varanasi Sri Aditya"
subtitle: "See the world through my eyes!"
author: "Varanasi Sri Aditya"
header:
 title: "Photography"
 subtitle: "by Varanasi Sri Aditya"
footer:
 name: "Hey there, my name is Aditya"
 bio: "I am a developer and photographer from India"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/vsasphotography"
  twitter: "https://www.twitter.com/vsriaditya"
  instagram: "https://www.instagram.com/vsasphotography"
  linkedin: "https://in.linkedin.com/in"
  github: "https://www.github.com/vsriaditya"
